In [11]:
import numpy as np

In [12]:
# Ques-->01 A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.
marks = np.array([[88, 96, 95],
                 [72, 99, 91],
                 [98, 85, 97],
                 [60, 75, 80]])

bonus = np.array([5,2,8])
new_marks = bonus + marks
print(new_marks)
print(np.sum(new_marks > 100))
final_marks = np.where(new_marks > 100, 100, new_marks)
print(final_marks)

[[ 93  98 103]
 [ 77 101  99]
 [103  87 105]
 [ 65  77  88]]
4
[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]


In [13]:
#Ques-->02 Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

a = np.ones((5, 5), dtype=int)
a[1:4, 1:4] = 0

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Ques-->03 Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

np.arange(30).reshape(5,-1).T


# one by one pehle toh ek array banega 0 se 30 tak ka 
# second : 5 aur -1 toh 5 cross 6 ka matrix banega 
# third: .t se matrix transpose hoga 
# array([[ 0,  6, 12, 18, 24],
    #    [ 1,  7, 13, 19, 25],
    #    [ 2,  8, 14, 20, 26],
    #    [ 3,  9, 15, 21, 27],
    #    [ 4, 10, 16, 22, 28],
    #    [ 5, 11, 17, 23, 29]])


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [ ]:
# Ques-->04 Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

h_stack = np.hstack((heights,weights))
print(h_stack.size)
# agar 2 one d arrays ko h_stack krenge toh 1 one d array hi milega 

X = np.column_stack((heights, weights))
print(X)

8
[[172  68]
 [158  52]
 [181  84]
 [166  59]]


In [26]:
# Ques-->05 Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

quarters = sales.reshape(4,3)

avg = quarters.mean(axis=1)
print(avg)

best = np.argmax(avg)
highest = avg[best]

print(best)
print(highest)

[117.66666667 175.          95.         212.66666667]
3
212.66666666666666


In [30]:
# Ques-->06 Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])
b = a.reshape(-1,1)
print(a*b)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


In [33]:
# Ques-->07 Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

a = np.arange(1,21)
np.where(a%3==0,-1,a)

array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1, 16, 17,
       -1, 19, 20])

In [35]:
# Ques-->08 For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

X = np.array([[ 50, 1200, 3],
              [ 80, 1500, 9],
              [ 65, 900, 5],
              [ 95, 2000, 7]])

col_max = X.max(axis=0)
col_min = X.min(axis=0)   
X_scaled = (X - col_min) / (col_max - col_min)

print(X_scaled)



[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]


In [41]:
# Ques-->09 Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
medals = np.where(scores>=90,"Gold",
         np.where(scores>=75,"Silver",
                  np.where(scores>=60,"Bronze","None")))

print("Gold:", np.sum(medals == "Gold"))
print("Silver:", np.sum(medals == "Silver"))
print("Bronze:", np.sum(medals == "Bronze"))
print("None:", np.sum(medals == "None"))

Gold: 2
Silver: 2
Bronze: 2
None: 2


In [ ]:
# Ques-->10 Given the matrix below, use np.where with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)
print(m[rows, cols])

m_copy = m.copy()
m_copy[rows, cols] = 0

print(m_copy)


[80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]


In [53]:
#Ques-->11 Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rows = np.vstack((s1,s2,s3))
columns = np.column_stack((s1,s2,s3))
print(rows)
print(columns)

row_1=rows.T
print(np.array_equal(row_1, columns))


[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
True


In [77]:
# Ques-->12 Create a random 6x6 matrix with seed = 1 and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.


# 1. Create random 6×6 matrix
# 2. Find maximum of EACH ROW
# 3. Find minimum of EACH COLUMN

np.random.seed(1)
a = np.random.randint(1, 101, (6, 6))
row_max = np.max(a, axis=1)
col_min = np.min(a, axis=0)

print(a)
print(row_max)
print(col_min)

[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
[76 80 85 69 97 64]
[ 7  8 17  2 19  6]


In [ ]:
# Ques-->13  A and B are both 2x3 matrices. Compute A @ B.T and A.T @ B. Print the shape of each result and explain in a comment why both multiplications are legal while A @ B is not.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])
a_trans = A.T
b_trans = B.T

m = A@b_trans
n = a_trans@B

print(m.shape)
print(n.shape)

# A@B is not possible b bcz both are 2 cross 3 matrix 


(2, 2)
(3, 3)


In [57]:
# Ques-->14 Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by w = [0.5, 0.2, 0.3] to obtain one score per row. Finally use np.where to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

X = np.hstack((hours_col,attendance_col))

totals = X.sum(axis=1)
totals = totals.reshape(-1, 1)

X_3 = np.hstack((X, totals))

w = [0.5, 0.2, 0.3]
scores = X_3 @ w

avg = scores.mean()

result = np.where(scores > avg, 1, 0)
print(result)

[0 1 0 1 0 1]


In [76]:
# Ques-->15  Apply min-max normalization to scale any array into the 0 to 1 range using (x-min)/(max-min).

x = np.array([10, 20, 30, 40, 50])
minimum = x.min()
maximum = x.max()
normalized = (x - minimum) / (maximum - minimum)
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Ques-->16 Take the array below and create two 1D versions of it — one with flatten() and one with ravel(). Change the first element of each, then print the original matrix. Explain the difference you observe in a comment.
m = np.array([[4, 8, 15],
 [16, 23, 42]])

fl = m.flatten()
ra = m.ravel()

fl[0] = 999
ra[0] = 998

print(m)
print(fl)
print(ra)


# ravel() → can change the original array's data
# flatten() → COPY

[[998   8  15]
 [ 16  23  42]]
[999   8  15  16  23  42]
[998   8  15  16  23  42]


In [74]:
# Ques-->17 28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each week's average, identify the hottest week, and count how many individual days crossed 35 degrees.

np.random.seed(7)
temps = np.random.randint(15, 41, 28)

temps = np.reshape(temps,(4,7))
avg = np.mean(temps,axis=1)
hottest = np.argmax(temps)
hot_days = np.sum(temps > 35)

print(avg)
print(hottest)
print(hot_days)

[30.85714286 31.57142857 23.28571429 26.85714286]
2
7


In [ ]:
# Ques-->18 Create two random 3x3 matrices A and B, compute A @ B and B @ A, and check whether the two results are equal. State your conclusion about matrix multiplication in a comment.

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

m = A@B
n = B@A
o = m.T

print(np.array_equal(m, n))



False
False


In [66]:
# Ques-->19 Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35, then compute each student's total, and finally print the index of the topper along with their total.

marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks = np.where(marks<35,35,marks)
st_total = marks.sum(axis=1)
topper = np.argmax(st_total)

print(st_total)
print(st_total[topper])

[227 221 231 342 165]
342


In [ ]:
# Ques-->20 Start from arr = np.arange(1, 11). Create one variable using a plain slice arr[2:6] and another using arr[2:6].copy(). Change the first element of each to 999, then print the original array and explain in a comment which change survived and why.

arr = np.arange(1, 11)

a = arr[2:6]          
b = arr[2:6].copy()

a[0] = 999
b[0] = 999

print(a)
print(b)
print(arr)


# a is a view, so changing a also changes the original arr.
# b is a copy, so changing b does not affect the original arr.


[999   4   5   6]
[999   2   3   4   5   6   7   8   9  10]


In [ ]:
# Ques-->21 Explore np.diag in the NumPy documentation and use it to extract the diagonal of a 4x4 matrix. Then use the same function in its second role — to build a diagonal matrix from a 1D array.

a = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15, 16]
])

print(np.diag(a))

b = np.array([2, 4, 6, 8])
matrix = np.diag(b)
print(matrix)



# np.diag(2D array) → extracts diagonal → 1D
# np.diag(1D array) → creates diagonal matrix → 2D


[ 1  6 11 16]
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
