In [1]:
import numpy as np


In [4]:
# Ques-->01
arr = np.arange(1, 24, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
# Ques-->02
arr = np.linspace(5,45,9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [6]:
# Ques-->03
arr_1 = np.arange(1,10)
arr_2 = np.linspace(1, 9, 9)

print(arr_1)
print(arr_2)

print(arr_1.dtype)
print(arr_2.dtype)




[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64
float64


In [12]:
# Ques-->04

m = np.eye(6, dtype=int)
print(m)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [13]:
# Ques-->05
m = np.full((3,4),5)
print("shape:",m.shape)
print("size:",m.size)
print("ndim:",m.ndim)

shape: (3, 4)
size: 12
ndim: 2


In [17]:
# Ques-->06

a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

m = a.dtype
n = b.dtype

print(m,n)

c = b.astype(int)
print(a.dtype, c.dtype)


int64 float64
int64 int64


In [ ]:
# Ques-->07
a = np.array([10.9, 25.5, 39.99]).astype(int) # prints--> [10,25,39] bcz it truncates float decimals
print(a)

[10 25 39]


In [ ]:
# Ques -->08
arr = np.arange(10, 101, 10) #arr =[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(arr[3])
print(arr[-1])
print(arr[-2])

40
100
90


In [22]:
# Ques-->09
arr = np.arange(10, 101, 10)
print(arr[2:6])
print(arr[::-1])

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


In [24]:
# Ques-->10
arr = np.arange(1, 21) #arr=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(arr[1:21:3])

[ 2  5  8 11 14 17 20]


In [26]:
#Ques-->11
arr = np.arange(1, 21)
print(arr[2:18])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [30]:
# Ques-->12
m = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[3])
print(m[:,4])
print(m[1:4,1:4])



[16 17 18 19 20]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [31]:
# Ques-->13
m = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
print(m[::4, ::4])

[[ 1  5]
 [21 25]]


In [32]:
# Ques-->14
m = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[0::2,0::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [35]:
# Ques-->15
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

print(marks[marks>60])
print(marks[(marks>50) & (marks<80)])

[91 77 62 85 70]
[56 77 62 70]
