In [3]:
import numpy as np 

In [ ]:
# 2.0 Creating Arrays

# 2.1From Python lists: np.array()

a = np.array([10, 20, 30])
m = np.array([[1, 2, 3],
             [4, 5, 6]]) #(2row x 3column) matrix

print("1 D matrix",a)
print("2 d matrix:\n",m)

1 D matrix [10 20 30]
2 d matrix:
 [[1 2 3]
 [4 5 6]]


In [15]:
# Mixed types trap (silently upcasts everything to strings)
mixed = np.array([1, 2, "three"])

print(mixed.dtype)

<U21


In [4]:
#2.2 Array generators: zeros, ones, full
z = np.zeros((2,3))   #2x3 matrix of 0s(The output shows 0. with a decimal point because the default dtype of these generators is float64,not int.)
o = np.ones(5)        #1D array of five 1s(The output shows 1. with a decimal point because the default dtype of these generators is float64, not int.)
f = np.full((3,3),7)  #3x3 matrix filled with 7
e = np.eye(4)         #4x4 matrix, 1s on the diagonal, 0s elsewhere

print(z)
print(o)
print(f)
print(e)


[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#2.3 Sequences: arange vs linspace
seq_arrange = np.arange(1,11,2)         # Stop excluded -> [1, 3, 5, 7, 9]
seq_linespace = np.linspace(0,10,5)     # Stop included -> [0., 2.5, 5., 7.5, 10.](start,stop,num)(step size = stop-start/num-1)(add step size)

print(seq_arrange)
print(seq_linespace)

[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# 2.4 Changing Data Types
floats = np.array([3.9, 7.8])
ints = floats.astype(int)       #arr.astype(): Converts array data types (truncates float decimals when converting to int)
#truncates:This means it simply cuts off everything after the decimal point without rounding up or down.
print(ints)

[3 7]


In [ ]:
# 3.0  Array Attributes

m = np.array([[1, 2, 3],
              [4, 5, 6]])

s = m.shape
n = m.ndim 
si = m.size
dt = m.dtype
l = len(m)

print(s)
print(n)
print(si)
print(dt)
print(l)


# len(arr) returns only the first dimension: for a (3, 4) matrix, len is 3 while .size is 12.

#These are attributes, not methods - no parentheses. m.shape() raises an error. In practice you will check .shape constantly: most ML bugs are shape bugs.

(2, 3)
2
6
int64
2


In [24]:
# 4.0 Indexing and Slicing

# 4.1 Indexing a 1D array

arr = np.array([10, 20 ,30, 40, 50])

print("First Element:",arr[0])
print("Last Element:",arr[-1])
print("Slice[1:4]",arr[1:4])
print("Reversed:",arr[::-1])

First Element: 10
Last Element: 50
Slice[1:4] [20 30 40]
Reversed: [50 40 30 20 10]


In [ ]:
# 4.2 Indexing and slicing a 2D array

m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Row 1, Column 2:", m[1, 2])  
print("Entire Row 1:", m[1])  
print("Entire Column 2:", m[:, 2])  
print("Sub-matrix (rows 0-1, cols 1-2):\n", m[0:2, 1:3])

Row 1, Column 2: 6
Entire Row 1: [4 5 6]
Entire Column 2: [[1 2 3]
 [4 5 6]]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


In [4]:
# 4.3 Boolean indexing (filtering)

marks = np.array([45, 82, 67, 33, 91])  
print("Boolean Mask (> 60):", marks > 60)  
print("Passed Marks:", marks[marks > 60])

filtered_marks = marks[(marks > 50) & (marks < 80)] 
print("Marks between 50 and 80:", filtered_marks)

Boolean Mask (> 60): [False  True  True False  True]
Passed Marks: [82 67 91]
Marks between 50 and 80: [67]


In [5]:
#5.0 Array Operations

#5.1 Element-wise Operations
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition :",a+b)
print("Multiplication :",a*b)
print("Power :",b**2)



Addition : [11 22 33 44]
Multiplication : [ 10  40  90 160]
Power : [ 1  4  9 16]


In [8]:
#5.2 Universal Functions

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Square Root :", np.sqrt(a))
print("Exponential :", np.exp(b)) #e^x


Square Root : [3.16227766 4.47213595 5.47722558 6.32455532]
Exponential : [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#6.0 The np.random Module

#6.1 random seed and random.rand
np.random.seed(42) #"Ek hi random value rehti hai barr barr change nhi hoti hai"
print(np.random.rand()) #This generates random floating-point numbers between 0 and 1.
print(np.random.rand(5))#np.random.rand(x) --> toh yeh 5 different random floating point numbers dega bw 0 and 1.
print(np.random.rand(2,3)) #Create a 2 × 3 array containing random numbers between 0 and 1.


0.3745401188473625
[0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]
-0.4694743859349521


In [20]:
#6.2 np.random.randn

print(np.random.randn()) #The important thing is randn() can generate both positive AND negative numbers.
print(np.random.randn(2, 3))#Create a 2 × 3 array. Values can be less than -1 or greater than 1

0.5425600435859647
[[-0.46341769 -0.46572975  0.24196227]
 [-1.91328024 -1.72491783 -0.56228753]]


In [ ]:
#6.3 np.random.randint()

#np.random.randint(low, high)
print(np.random.randint(1, 10)) #excluding 10 any random integer bw low and high. 

# randint() with size
print(np.random.randint(1, 7, size=5)) #Generate 5 random integers from 1 to 6.

# 2D array with randint
print(np.random.randint(1, 10, size=(2, 3))) # high excluded

7
[4 1 3 5 3]


In [25]:
# 6.4 np.random.choice() : This is used when you already have some values and want NumPy to randomly choose from them.
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr))

# Choosing multiple elements
print(np.random.choice(arr, size=3))


40
[20 20 10]


In [28]:
# 6.5 np.random.shuffle() : This one rearranges the elements of an array randomly

arr = np.array([1, 2, 3, 4, 5])
print(np.random.shuffle(arr)) #But shuffle() does not return the shuffled array.It just changes the array.
print(arr)

None
[2 1 3 4 5]


In [ ]:
#7.0 Basic Statistics

arr = np.array([10, 20, 30, 40, 50])
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr)) # for even numbers : mean of two middle values
print(np.std(arr)) #small std → values are closer together, large std → values are more spread out
print(np.var(arr)) #variance = (standard deviation)²
print(np.argmax(arr)) #returns the index of max value 
print(np.argmin(arr)) #returns the index of min value 



10
50
150
30.0
30.0
14.142135623730951
200.0
4
0


In [30]:
#7.1 Aggregations & Axes

a = np.array([10, 20, 30, 40])
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Total Sum :",np.sum(m))
print("Column Sum :",np.sum(m,axis=0))
print("Row Sum :",np.sum(m,axis=1) )
print("Index of max value :",np.argmax(m)) #np.argmax(m) flattens the array into a 1D sequence and returns 5

Total Sum : 21
Column Sum : [5 7 9]
Row Sum : [ 6 15]
Index of max value : 5
