In [4]:
import numpy as np

In [5]:
#1.0 BRODCASTING
# When shapes differ, NumPy "stretches" the smaller array to fit the bigger one
#The stretching is virtual - no copies are made in memory, which is why it stays fast

#1.1 A 2D matrix with a 1D row

m = np.ones((3,3)) #shape = (3,3)
row = np.array([10,20,30]) #shape =(3,)
print(m + row)

#"stretching" the smaller array to fit the bigger array when their shapes differ

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [6]:
# 1.2 Broadcasting with a column vector
col = np.array([[1], [2], [3]]) #shape = (1,3)
row = np.array([10, 20, 30]) #shape = (3,)--> 1d matrix 

print(col+row)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [7]:
#1.3 The broadcasting rule

#Rule 1: Compare shapes from RIGHT → LEFT
#Rule 2: Two dimensions are compatible if: 001. They are EQUAL OR 002. One of them is 1


# 1.4 Practical Use: Column-wise Normalization
X = np.array([
    [170, 65],
    [155, 50],
    [180, 80],
    [165, 58]
]) #shape: (4,2)
col_mean = X.mean(axis=0) # gives ans for each column when axis is 0
row_mean = X.mean(axis=1) # gives ans for each row when axis is 1

print(col_mean)
print(row_mean)


[167.5   63.25]
[117.5 102.5 130.  111.5]


In [8]:
#2.0 Reshaping and Dimensions

#2.1 Reshape(rows, columns) 
# RULES: 01.rows x columns must equal the total number of elements
       # 02.Filling order is row by row, left to right
       # 03.With 12 elements you can ask for (3,4), (4,3), (2,6), (6,2), (12,1), (1,12) - any product of 12

arr = np.arange(1, 13)
m = arr.reshape(3, 4)
# arr.reshape(3, 5) #will not work bcz 3*5 will be 15!=12
print(arr) #reshape() doesn't change arr itself
print(m)# If we want to keep the reshaped version


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
#2.2 The -1 Trick :can only use one -1.
arr = np.arange(1, 13)
print(arr.reshape(3, -1)) #NumPy divides the total size by the dimension you did specify 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#2.3 reshape(-1, 1): turning a list into a column
arr = np.arange(1, 13)
print(arr.reshape(-1, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [11]:
#2.4 flatten() vs ravel(): Convert a multi-dimensional array into a 1D array.
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

f = m.flatten()
r = m.ravel()

print("flatten:", f)
print("ravel :", r)

f = m.flatten()
f[1] = 999

r = m.ravel()
r[1] = 888
print(m) #ravel wala change hua array main but flatten wale ne nhi kiya 
# ravel() → can change the original array's data
# flatten() → COPY

flatten: [1 2 3 4 5 6]
ravel : [1 2 3 4 5 6]
[[  1 888   3]
 [  4   5   6]]


In [12]:
# 2.5 np.newaxis: np.newaxis inserts a new dimension of size 1 wherever you place it

marks = np.array([65, 70, 88, 92])
as_column = marks[:, np.newaxis] #np.newaxis agar peeche likha ho toh column bann jaayega
as_row = marks[np.newaxis, :] #np.newaxis agar aage likha ho toh row bann jaayegi

print(as_column)
print(as_row)



[[65]
 [70]
 [88]
 [92]]
[[65 70 88 92]]


In [13]:
#3.0 Stacking and Combining Arrays

#3.1: vstack and hstack

# vstack() — Vertical Stack: Put B vertically below A
#If you're stacking vertically, the number of columns must match
A = np.array([
    [1, 2, 3],    
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9]
])

C = np.array([
    [10],
    [20]
])
print(np.vstack((A, B)))
print(np.hstack((A, C)))

# A → 2 rows
# B → 1 row
#      ------
#      3 rows
# Columns remain → 3


# Rows:
# 2 = 2          → stay the same
# Columns:
# 3 + 1 = 4      → columns grow


# hstack() — Horizontal Stack: we put them side by side
                             # rows must match

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 20]]


In [14]:
# 3.2 The 1D hstack() Surprise
heights = np.array([170, 155, 180, 165])
weights = np.array([65, 50, 80, 58])

print(np.hstack((heights, weights))) # chaiyeh hum height ka ek column aur weigth ka ek but ek 1d array mil raha hai toh no error but error

# toh pehle hum convert krenge proper column main using reshape(-1, 1)
heights.reshape(-1, 1)
weights.reshape(-1, 1)

X = np.hstack((
    heights.reshape(-1, 1),
    weights.reshape(-1, 1)
))
print(X)

[170 155 180 165  65  50  80  58]
[[170  65]
 [155  50]
 [180  80]
 [165  58]]


In [15]:
# 3.3 np.column_stack() — the cleaner solution
heights = np.array([170, 155, 180, 165])
weights = np.array([65, 50, 80, 58])

X = np.column_stack((heights, weights))
print(X) #hstack wala problem fix kr diya zyada lengthy nhi hoga 

[[170  65]
 [155  50]
 [180  80]
 [165  58]]


In [16]:
#3.4 np.concatenate() — General-purpose joining
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(np.concatenate((A, B), axis=0)) #columnwise
print(np.concatenate((A, B), axis=1)) #rowwise


# axis=0 → rows direction ↓
#          more rows

# axis=1 → columns direction →
#          more columns

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [17]:
#4.0 Conditional Logic 

#4.1 np.where() : #np.where(condition, value_if_true, value_if_false)
scores = np.array([45, 72, 88, 33, 60])
result = np.where(scores >= 60, "Pass", "Fail")

print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass']


In [ ]:
#4.2 np.where() with numbers
scores = np.array([45, 72, 88, 33, 60])
curved = np.where(scores < 50, scores + 5, scores)

print(curved)

# scores:        [45     72     88     33     60]
# condition:     [ T      F      F      T      F ]

# scores + 5:    [50     77     93     38     65]
# scores:        [45     72     88     33     60]
#                 ↓      ↓      ↓      ↓      ↓
# chosen:        [50     72     88     38     60]

[50 72 88 38 60]


In [20]:
#4.3 Nested np.where()
scores = np.array([45, 72, 88, 33, 60])
grade = np.where(
    scores >= 80, "A",
    np.where(scores >= 60, "B", "C")
)

print(grade)

['C' 'B' 'A' 'C' 'B']


In [ ]:
#5.0 Linear Algebra — Matrix Multiplication
# matrix wala hi multiplication hai
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A@B)
print(np.dot(A,B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [22]:
#5.1 Matrix Multiplication — Shape Rule

# (m, n) @ (n, p)
#     ↑      ↑
#     └──────┘
#     must match
# shape of multiplied matrix: (m, p)

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

m = A@B 
print(np.shape(m))

(2, 2)


In [ ]:
#5.2 Transpose: Rows become columns, and columns become rows.
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)

# transpose of shape of one d array will be (n,) never (,n)
B = np.array([1,2,3])

print((B.T))
print(np.shape(B.T))

[[1 4]
 [2 5]
 [3 6]]
[1 2 3]
(3,)


In [ ]:
#5.3 Determinant(np.linalg.det()) and Inverse(np.linalg.inv()): matrices wala hi determinant

M = np.array([
    [4, 7],
    [2, 6]
])

print(np.linalg.det(M))
print(np.linalg.inv(M)) # inverse bhi same matrice wala:
                        #step01 check determinant!= ZERO
                        #step02 inverse matrice = 1/determinant * adj matrice
                        #step 03 adj matrice = transpose of co-factor matrice
                        #step 04 co factor matrice : determinat wla method aur ek ek chodh kr -ve



10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#6.0 Copy vs View: wahi flatten aur ravel

original = np.array([10, 20, 30, 40, 50])


view = original[1:4]
print(view)
view[0] = 999
print(view)
print(original)

copy = original[1:4].copy()
print(copy)
copy[0] = 999
print(copy)
print(original)

# copy wala change nhi kiya main array main but view wale ne kiya 


# VIEW                         COPY

# shares data                  independent data
#    ↓                              ↓
# change view                  change copy
#    ↓                              ↓
# original can change          original doesn't change

[20 30 40]
[999  30  40]
[ 10 999  30  40  50]
[999  30  40]
[999  30  40]
[ 10 999  30  40  50]
